const ClientProt = {
    DEBUG_INFO: 17,
    REPORT_ABUSE: 51,
    //
    APPEARANCE: 236,
    BANK_CLOSE: 207,
    BANK_DEPOSIT: 205,
    BANK_WITHDRAW: 206,
    SPELLGROUND: 221,
    SPELLOBJ: 224,
    SPELLINV: 220,
    SPELLNPC: 225,
    SPELLLOC: 222,
    SPELLPLAYER: 226,
    SPELLSELF: 227,
    SPELLBOUND: 223,
    CHANGE_PASSWORD: 25,
    MESSAGE_PUBLIC: 3,
    CHOOSE_OPTION: 237,
    CLOSE_CONNECTION: 1,
    COMBAT_STYLE: 231,
    CLIENT_CHEAT: 7,
    DUEL_ACCEPT: 199,
    DUEL_CONFIRM_ACCEPT: 198,
    DUEL_DECLINE: 203,
    DUEL_ITEM_UPDATE: 201,
    DUEL_OPTIONS: 200,
    FRIENDLIST_ADD: 26,
    FRIENDLIST_DEL: 27,
    TAKEOBJ: 252,
    IGNORELIST_ADD: 29,
    IGNORELIST_DEL: 30,
    OPINV: 246,
    DROPOBJ: 251,
    REMOVEOBJ: 248,
    WEAROBJ: 249,
    KNOWN_PLAYERS: 254,
    LOGIN: 0,
    RECONNECT: 19,
    LOGOUT: 6,
    ATTACKNPC: 244,
    NPC_COMMAND: 195, // TODO
    TALKNPC: 245,
    OPLOC1: 242,
    OPLOC2: 230,
    NO_TIMEOUT: 5,
    ATTACKPLAYER: 228,
    PLAYER_DUEL: 204,
    PLAYER_FOLLOW: 214,
    PLAYER_TRADE: 235,
    MESSAGE_PRIVATE: 28,
    PRAYER_OFF: 211,
    PRAYER_ON: 212,
    REGISTER: 2,
    SETTINGS_GAME: 213,
    CHAT_SETMODE: 31,
    SHOP_BUY: 217,
    SHOP_CLOSE: 218,
    SHOP_SELL: 216,
    SLEEP_WORD: 193,
    TRADE_ACCEPT: 232,
    TRADE_CONFIRM_ACCEPT: 202,
    TRADE_DECLINE: 233,
    TRADE_ITEM_UPDATE: 234,
    USEOBJ: 250,
    USEINV: 240,
    USENPC: 243,
    USELOC: 241,
    USEPLAYER: 219,
    USEBOUND: 239,
    MOVE_GAMECLICK: 194,
    MOVE_OPCLICK: 215,
    OPBOUND1: 238,
    OPBOUND2: 229,
};

// generate reverse lookup

for (let key in ClientProt) {
    ClientProt[ClientProt[key]] = key;
}

export default ClientProt;

export const CLIENT_ENCRYPTION = new Uint16Array(256);
for (let i = 0; i < CLIENT_ENCRYPTION.length; i++) {
    CLIENT_ENCRYPTION[i] = i % 10;
}
CLIENT_ENCRYPTION[ClientProt.RECONNECT] = 712;
CLIENT_ENCRYPTION[ClientProt.LOGIN] = 625;
CLIENT_ENCRYPTION[ClientProt.CLOSE_CONNECTION] = 325;
CLIENT_ENCRYPTION[ClientProt.REGISTER] = 129;
CLIENT_ENCRYPTION[ClientProt.NO_TIMEOUT] = 348;
CLIENT_ENCRYPTION[ClientProt.CHANGE_PASSWORD] = 551;
CLIENT_ENCRYPTION[ClientProt.CHAT_SETMODE] = 777;
CLIENT_ENCRYPTION[ClientProt.IGNORELIST_ADD] = 101;
CLIENT_ENCRYPTION[ClientProt.IGNORELIST_DEL] = 511;
CLIENT_ENCRYPTION[ClientProt.FRIENDLIST_ADD] = 622;
CLIENT_ENCRYPTION[ClientProt.FRIENDLIST_DEL] = 707;
CLIENT_ENCRYPTION[ClientProt.MESSAGE_PRIVATE] = 185;
CLIENT_ENCRYPTION[ClientProt.MESSAGE_PUBLIC] = 643;
CLIENT_ENCRYPTION[ClientProt.CLIENT_CHEAT] = 293;
CLIENT_ENCRYPTION[ClientProt.LOGOUT] = 156;
CLIENT_ENCRYPTION[208] = 457;
CLIENT_ENCRYPTION[253] = 155;
CLIENT_ENCRYPTION[ClientProt.APPEARANCE] = 65;
CLIENT_ENCRYPTION[4] = 848;
CLIENT_ENCRYPTION[8] = 121;
CLIENT_ENCRYPTION[ClientProt.SLEEP_WORD] = 127;
CLIENT_ENCRYPTION[ClientProt.KNOWN_PLAYERS] = 120;
CLIENT_ENCRYPTION[ClientProt.DEBUG_INFO] = 743;
CLIENT_ENCRYPTION[ClientProt.MOVE_OPCLICK] = 592;
CLIENT_ENCRYPTION[ClientProt.MOVE_GAMECLICK] = 770;
CLIENT_ENCRYPTION[ClientProt.CHOOSE_OPTION] = 3;
CLIENT_ENCRYPTION[ClientProt.COMBAT_STYLE] = 700;
CLIENT_ENCRYPTION[196] = 651;
CLIENT_ENCRYPTION[ClientProt.REPORT_ABUSE] = 277;
CLIENT_ENCRYPTION[ClientProt.BANK_WITHDRAW] = 655;
CLIENT_ENCRYPTION[ClientProt.BANK_DEPOSIT] = 523;
CLIENT_ENCRYPTION[ClientProt.BANK_CLOSE] = 886;
CLIENT_ENCRYPTION[ClientProt.SHOP_BUY] = 666;
CLIENT_ENCRYPTION[ClientProt.SHOP_SELL] = 665;
CLIENT_ENCRYPTION[ClientProt.SHOP_CLOSE] = 312;
CLIENT_ENCRYPTION[ClientProt.TRADE_DECLINE] = 235;
CLIENT_ENCRYPTION[ClientProt.TRADE_CONFIRM_ACCEPT] = 96;
CLIENT_ENCRYPTION[ClientProt.TRADE_ITEM_UPDATE] = 500;
CLIENT_ENCRYPTION[ClientProt.TRADE_ACCEPT] = 277;
CLIENT_ENCRYPTION[ClientProt.DUEL_CONFIRM_ACCEPT] = 412;
CLIENT_ENCRYPTION[ClientProt.DUEL_DECLINE] = 266;
CLIENT_ENCRYPTION[ClientProt.DUEL_ITEM_UPDATE] = 53;
CLIENT_ENCRYPTION[ClientProt.DUEL_OPTIONS] = 285;
CLIENT_ENCRYPTION[ClientProt.DUEL_ACCEPT] = 564;
CLIENT_ENCRYPTION[ClientProt.PRAYER_OFF] = 457;
CLIENT_ENCRYPTION[ClientProt.PRAYER_ON] = 126;
CLIENT_ENCRYPTION[ClientProt.SETTINGS_GAME] = 892;
CLIENT_ENCRYPTION[197] = 882;
CLIENT_ENCRYPTION[247] = 888;
CLIENT_ENCRYPTION[ClientProt.SPELLOBJ] = 821;
CLIENT_ENCRYPTION[ClientProt.USEOBJ] = 346;
CLIENT_ENCRYPTION[ClientProt.TAKEOBJ] = 634;
CLIENT_ENCRYPTION[ClientProt.SPELLBOUND] = 596;
CLIENT_ENCRYPTION[ClientProt.USEBOUND] = 792;
CLIENT_ENCRYPTION[ClientProt.OPBOUND1] = 212;
CLIENT_ENCRYPTION[ClientProt.OPBOUND2] = 726;
CLIENT_ENCRYPTION[ClientProt.SPELLLOC] = 555;
CLIENT_ENCRYPTION[ClientProt.USELOC] = 772;
CLIENT_ENCRYPTION[ClientProt.OPLOC1] = 863;
CLIENT_ENCRYPTION[ClientProt.OPLOC2] = 67;
CLIENT_ENCRYPTION[ClientProt.SPELLINV] = 567;
CLIENT_ENCRYPTION[ClientProt.USEINV] = 377;
CLIENT_ENCRYPTION[ClientProt.REMOVEOBJ] = 466;
CLIENT_ENCRYPTION[ClientProt.WEAROBJ] = 267;
CLIENT_ENCRYPTION[ClientProt.OPINV] = 237;
CLIENT_ENCRYPTION[ClientProt.DROPOBJ] = 664;
CLIENT_ENCRYPTION[ClientProt.SPELLNPC] = 824;
CLIENT_ENCRYPTION[ClientProt.USENPC] = 876;
CLIENT_ENCRYPTION[ClientProt.TALKNPC] = 586;
CLIENT_ENCRYPTION[ClientProt.NPC_COMMAND] = 543;
CLIENT_ENCRYPTION[ClientProt.ATTACKNPC] = 754;
CLIENT_ENCRYPTION[ClientProt.SPELLPLAYER] = 117;
CLIENT_ENCRYPTION[ClientProt.USEPLAYER] = 145;
CLIENT_ENCRYPTION[ClientProt.ATTACKPLAYER] = 414;
CLIENT_ENCRYPTION[ClientProt.PLAYER_DUEL] = 273;
CLIENT_ENCRYPTION[ClientProt.PLAYER_TRADE] = 636;
CLIENT_ENCRYPTION[ClientProt.PLAYER_FOLLOW] = 596;
CLIENT_ENCRYPTION[ClientProt.SPELLGROUND] = 545;
CLIENT_ENCRYPTION[ClientProt.SPELLSELF] = 411;
