const ClientProt = {
    APPEARANCE: 236,
    BANK_CLOSE: 207,
    BANK_DEPOSIT: 205,
    BANK_WITHDRAW: 206,
    CAST_GROUND: 221,
    CAST_GROUNDITEM: 224,
    CAST_INVITEM: 220,
    CAST_NPC: 225,
    CAST_OBJECT: 222,
    CAST_PLAYER: 226,
    CAST_SELF: 227,
    CAST_WALLOBJECT: 223,
    CHANGE_PASSWORD: 25,
    CHAT: 3,
    CHOOSE_OPTION: 237,
    CLOSE_CONNECTION: 1,
    COMBAT_STYLE: 231,
    COMMAND: 7,
    DUEL_ACCEPT: 199,
    DUEL_CONFIRM_ACCEPT: 198,
    DUEL_DECLINE: 203,
    DUEL_ITEM_UPDATE: 201,
    DUEL_OPTIONS: 200,
    FRIEND_ADD: 26,
    FRIEND_REMOVE: 27,
    GROUNDITEM_TAKE: 252,
    IGNORE_ADD: 29,
    IGNORE_REMOVE: 30,
    INVENTORY_COMMAND: 246,
    INVENTORY_DROP: 251,
    INVENTORY_UNEQUIP: 248,
    INVENTORY_WEAR: 249,
    KNOWN_PLAYERS: 254,
    LOGIN: 0,
    RECONNECT: 19,
    LOGOUT: 6,
    NPC_ATTACK: 244,
    NPC_COMMAND: 195,
    NPC_TALK: 245,
    OBJECT_COMMAND1: 242,
    OBJECT_COMMAND2: 230,
    // PACKET_EXCEPTION: 3, // wrong
    PING: 5,
    PLAYER_ATTACK: 228,
    PLAYER_DUEL: 204,
    PLAYER_FOLLOW: 214,
    PLAYER_TRADE: 235,
    PM: 28,
    PRAYER_OFF: 211,
    PRAYER_ON: 212,
    // RECOVER_CANCEL: 196, // wrong
    // RECOVER_GET_QUESTIONS: 233, // wrong
    // RECOVER_REQUEST: 220, // wrong
    // RECOVER_SET: 208, // wrong
    // RECOVER_SET_REQUEST: 213, // wrong
    REGISTER: 2,
    // REPORT_ABUSE: 206, // wrong
    SETTINGS_GAME: 213,
    SETTINGS_PRIVACY: 31,
    SHOP_BUY: 217,
    SHOP_CLOSE: 218,
    SHOP_SELL: 216,
    SLEEP_WORD: 193,
    TRADE_ACCEPT: 232,
    TRADE_CONFIRM_ACCEPT: 202,
    TRADE_DECLINE: 233,
    TRADE_ITEM_UPDATE: 234,
    USEWITH_GROUNDITEM: 250,
    USEWITH_INVITEM: 240,
    USEWITH_NPC: 243,
    USEWITH_OBJECT: 241,
    USEWITH_PLAYER: 219,
    USEWITH_WALLOBJECT: 239,
    WALK: 194,
    WALK_ACTION: 215,
    WALL_OBJECT_COMMAND1: 238,
    WALL_OBJECT_COMMAND2: 229,
};

// generate reverse lookup

for (let key in ClientProt) {
    ClientProt[ClientProt[key]] = key;
}

export default ClientProt;

export const CLIENT_ENCRYPTION = new Uint16Array(256);
for (let i = 0; i < CLIENT_ENCRYPTION.length; i++) {
    CLIENT_ENCRYPTION[i] = i % 10;
}
CLIENT_ENCRYPTION[ClientProt.RECONNECT] = 712;
CLIENT_ENCRYPTION[ClientProt.LOGIN] = 625;
CLIENT_ENCRYPTION[ClientProt.CLOSE_CONNECTION] = 325;
CLIENT_ENCRYPTION[ClientProt.REGISTER] = 129;
CLIENT_ENCRYPTION[ClientProt.PING] = 348;
CLIENT_ENCRYPTION[ClientProt.CHANGE_PASSWORD] = 551;
CLIENT_ENCRYPTION[ClientProt.SETTINGS_PRIVACY] = 777;
CLIENT_ENCRYPTION[ClientProt.IGNORE_ADD] = 101;
CLIENT_ENCRYPTION[ClientProt.IGNORE_REMOVE] = 511;
CLIENT_ENCRYPTION[ClientProt.FRIEND_ADD] = 622;
CLIENT_ENCRYPTION[ClientProt.FRIEND_REMOVE] = 707;
CLIENT_ENCRYPTION[ClientProt.PM] = 185;
CLIENT_ENCRYPTION[ClientProt.CHAT] = 643;
CLIENT_ENCRYPTION[ClientProt.COMMAND] = 293;
CLIENT_ENCRYPTION[ClientProt.LOGOUT] = 156;
CLIENT_ENCRYPTION[208] = 457;
CLIENT_ENCRYPTION[253] = 155;
CLIENT_ENCRYPTION[ClientProt.APPEARANCE] = 65;
CLIENT_ENCRYPTION[4] = 848;
CLIENT_ENCRYPTION[8] = 121;
CLIENT_ENCRYPTION[ClientProt.SLEEP_WORD] = 127;
CLIENT_ENCRYPTION[ClientProt.KNOWN_PLAYERS] = 120;
CLIENT_ENCRYPTION[17] = 743;
CLIENT_ENCRYPTION[ClientProt.WALK_ACTION] = 592;
CLIENT_ENCRYPTION[ClientProt.WALK] = 770;
CLIENT_ENCRYPTION[ClientProt.CHOOSE_OPTION] = 3;
CLIENT_ENCRYPTION[ClientProt.COMBAT_STYLE] = 700;
CLIENT_ENCRYPTION[196] = 651;
CLIENT_ENCRYPTION[51] = 277;
CLIENT_ENCRYPTION[ClientProt.BANK_WITHDRAW] = 655;
CLIENT_ENCRYPTION[ClientProt.BANK_DEPOSIT] = 523;
CLIENT_ENCRYPTION[ClientProt.BANK_CLOSE] = 886;
CLIENT_ENCRYPTION[ClientProt.SHOP_BUY] = 666;
CLIENT_ENCRYPTION[ClientProt.SHOP_SELL] = 665;
CLIENT_ENCRYPTION[ClientProt.SHOP_CLOSE] = 312;
CLIENT_ENCRYPTION[ClientProt.TRADE_DECLINE] = 235;
CLIENT_ENCRYPTION[ClientProt.TRADE_CONFIRM_ACCEPT] = 96;
CLIENT_ENCRYPTION[ClientProt.TRADE_ITEM_UPDATE] = 500;
CLIENT_ENCRYPTION[ClientProt.TRADE_ACCEPT] = 277;
CLIENT_ENCRYPTION[ClientProt.DUEL_CONFIRM_ACCEPT] = 412;
CLIENT_ENCRYPTION[ClientProt.DUEL_DECLINE] = 266;
CLIENT_ENCRYPTION[ClientProt.DUEL_ITEM_UPDATE] = 53;
CLIENT_ENCRYPTION[ClientProt.DUEL_OPTIONS] = 285;
CLIENT_ENCRYPTION[ClientProt.DUEL_ACCEPT] = 564;
CLIENT_ENCRYPTION[ClientProt.PRAYER_OFF] = 457;
CLIENT_ENCRYPTION[ClientProt.PRAYER_ON] = 126;
CLIENT_ENCRYPTION[ClientProt.SETTINGS_GAME] = 892;
CLIENT_ENCRYPTION[197] = 882;
CLIENT_ENCRYPTION[247] = 888;
CLIENT_ENCRYPTION[ClientProt.CAST_GROUNDITEM] = 821;
CLIENT_ENCRYPTION[ClientProt.USEWITH_GROUNDITEM] = 346;
CLIENT_ENCRYPTION[ClientProt.GROUNDITEM_TAKE] = 634;
CLIENT_ENCRYPTION[ClientProt.CAST_WALLOBJECT] = 596;
CLIENT_ENCRYPTION[ClientProt.USEWITH_WALLOBJECT] = 792;
CLIENT_ENCRYPTION[ClientProt.WALL_OBJECT_COMMAND1] = 212;
CLIENT_ENCRYPTION[ClientProt.WALL_OBJECT_COMMAND2] = 726;
CLIENT_ENCRYPTION[ClientProt.CAST_OBJECT] = 555;
CLIENT_ENCRYPTION[ClientProt.USEWITH_OBJECT] = 772;
CLIENT_ENCRYPTION[ClientProt.OBJECT_COMMAND1] = 863;
CLIENT_ENCRYPTION[ClientProt.OBJECT_COMMAND2] = 67;
CLIENT_ENCRYPTION[ClientProt.CAST_INVITEM] = 567;
CLIENT_ENCRYPTION[ClientProt.USEWITH_INVITEM] = 377;
CLIENT_ENCRYPTION[ClientProt.INVENTORY_UNEQUIP] = 466;
CLIENT_ENCRYPTION[ClientProt.INVENTORY_WEAR] = 267;
CLIENT_ENCRYPTION[ClientProt.INVENTORY_COMMAND] = 237;
CLIENT_ENCRYPTION[ClientProt.INVENTORY_DROP] = 664;
CLIENT_ENCRYPTION[ClientProt.CAST_NPC] = 824;
CLIENT_ENCRYPTION[ClientProt.USEWITH_NPC] = 876;
CLIENT_ENCRYPTION[ClientProt.NPC_TALK] = 586;
CLIENT_ENCRYPTION[ClientProt.NPC_COMMAND] = 543;
CLIENT_ENCRYPTION[ClientProt.NPC_ATTACK] = 754;
CLIENT_ENCRYPTION[ClientProt.CAST_PLAYER] = 117;
CLIENT_ENCRYPTION[ClientProt.USEWITH_PLAYER] = 145;
CLIENT_ENCRYPTION[ClientProt.PLAYER_ATTACK] = 414;
CLIENT_ENCRYPTION[ClientProt.PLAYER_DUEL] = 273;
CLIENT_ENCRYPTION[ClientProt.PLAYER_TRADE] = 636;
CLIENT_ENCRYPTION[ClientProt.PLAYER_FOLLOW] = 596;
CLIENT_ENCRYPTION[ClientProt.CAST_GROUND] = 545;
CLIENT_ENCRYPTION[ClientProt.CAST_SELF] = 411;
