const ServerProt = {
    APPEARANCE: 239,
    BANK_CLOSE: 221,
    BANK_OPEN: 222,
    BANK_UPDATE: 214,
    LOGOUT: 9,
    DUEL_ACCEPTED: 209,
    DUEL_CLOSE: 218,
    DUEL_CONFIRM_OPEN: 208,
    DUEL_OPEN: 219,
    DUEL_RECIPIENT_ACCEPTED: 210,
    DUEL_SETTINGS: 215,
    DUEL_ITEMS: 216,
    FRIEND_LIST: 23,
    FRIEND_MESSAGE: 28,
    FRIEND_STATUS_CHANGE: 24,
    GAME_SETTINGS: 228,
    IGNORE_LIST: 26,
    UPDATE_INV_FULL: 252,
    INVENTORY_ITEM_REMOVE: 212,
    UPDATE_INV_PARTIAL: 213,
    LOGOUT_DENY: 10,
    MESSAGE_GAME: 8,
    OPTION_LIST: 246,
    OPTION_LIST_CLOSE: 245,
    PLAYER_DIED: 241,
    PLAYER_QUEST_LIST: 226,
    PLAYER_STAT_EQUIPMENT_BONUS: 242,
    PLAYER_STAT_EXPERIENCE_UPDATE: 220,
    PLAYER_STAT_FATIGUE: 202,
    PLAYER_STAT_FATIGUE_ASLEEP: 200,
    PLAYER_STAT_LIST: 243,
    PLAYER_STAT_UPDATE: 211,
    PRAYER_STATUS: 227,
    CHAT_FILTER_SETTINGS: 27,
    REGION_ENTITY_UPDATE: 240,
    REGION_GROUND_ITEMS: 254,
    NPC_INFO: 248,
    REGION_NPC_UPDATE: 247,
    REGION_OBJECTS: 253, // Scenery
    PLAYER_INFO: 255,
    REGION_PLAYER_UPDATE: 250,
    REGION_WALL_OBJECTS: 249, // Boundary
    MESSAGE_ONTOP: 203,
    SHOP_CLOSE: 233,
    SHOP_OPEN: 234,
    SLEEP_CLOSE: 199,
    SLEEP_INCORRECT: 198,
    SLEEP_OPEN: 201,
    SYNTH_SOUND: 207,
    TELEPORT_BUBBLE: 206,
    TRADE_CLOSE: 237,
    TRADE_CONFIRM_OPEN: 217,
    TRADE_ITEMS: 236,
    TRADE_OPEN: 238,
    TRADE_RECIPIENT_ACCEPTED: 235,
    TRADE_ACCEPTED: 229,
    LAST_LOGIN_INFO: 205,
    REBUILD_NORMAL: 244
};

// generate reverse lookup

for (let key in ServerProt) {
    ServerProt[ServerProt[key]] = key;
}

export default ServerProt;

export const SERVER_ENCRYPTION = new Uint16Array(256);
for (let i = 0; i < SERVER_ENCRYPTION.length; i++) {
    SERVER_ENCRYPTION[i] = i % 10;
}
SERVER_ENCRYPTION[0] = 124;
SERVER_ENCRYPTION[1] = 345;
SERVER_ENCRYPTION[2] = 953;
SERVER_ENCRYPTION[3] = 124;
SERVER_ENCRYPTION[4] = 634;
SERVER_ENCRYPTION[5] = 636;
SERVER_ENCRYPTION[6] = 661;
SERVER_ENCRYPTION[7] = 127;
SERVER_ENCRYPTION[ServerProt.MESSAGE_GAME] = 177;
SERVER_ENCRYPTION[ServerProt.LOGOUT] = 295;
SERVER_ENCRYPTION[ServerProt.LOGOUT_DENY] = 559;
SERVER_ENCRYPTION[11] = 384;
SERVER_ENCRYPTION[12] = 321;
SERVER_ENCRYPTION[13] = 679;
SERVER_ENCRYPTION[14] = 871;
SERVER_ENCRYPTION[15] = 592;
SERVER_ENCRYPTION[16] = 679;
SERVER_ENCRYPTION[17] = 347;
SERVER_ENCRYPTION[18] = 926;
SERVER_ENCRYPTION[19] = 585;
SERVER_ENCRYPTION[20] = 681;
SERVER_ENCRYPTION[21] = 195;
SERVER_ENCRYPTION[22] = 785;
SERVER_ENCRYPTION[ServerProt.FRIEND_LIST] = 679;
SERVER_ENCRYPTION[ServerProt.FRIEND_STATUS_CHANGE] = 818;
SERVER_ENCRYPTION[25] = 115;
SERVER_ENCRYPTION[ServerProt.IGNORE_LIST] = 226;
SERVER_ENCRYPTION[ServerProt.CHAT_FILTER_SETTINGS] = 799;
SERVER_ENCRYPTION[ServerProt.FRIEND_MESSAGE] = 925;
SERVER_ENCRYPTION[29] = 852;
SERVER_ENCRYPTION[30] = 194;
SERVER_ENCRYPTION[31] = 966;
SERVER_ENCRYPTION[32] = 32;
SERVER_ENCRYPTION[40] = 40;
SERVER_ENCRYPTION[50] = 50;
SERVER_ENCRYPTION[51] = 444;
SERVER_ENCRYPTION[52] = 52;
SERVER_ENCRYPTION[60] = 60;
SERVER_ENCRYPTION[70] = 70;
SERVER_ENCRYPTION[80] = 80;
SERVER_ENCRYPTION[90] = 90;
SERVER_ENCRYPTION[100] = 100;
SERVER_ENCRYPTION[110] = 110;
SERVER_ENCRYPTION[120] = 120;
SERVER_ENCRYPTION[130] = 130;
SERVER_ENCRYPTION[140] = 140;
SERVER_ENCRYPTION[150] = 150;
SERVER_ENCRYPTION[160] = 160;
SERVER_ENCRYPTION[170] = 170;
SERVER_ENCRYPTION[180] = 180;
SERVER_ENCRYPTION[190] = 694;
SERVER_ENCRYPTION[191] = 235;
SERVER_ENCRYPTION[192] = 846;
SERVER_ENCRYPTION[193] = 834;
SERVER_ENCRYPTION[194] = 300;
SERVER_ENCRYPTION[195] = 200;
SERVER_ENCRYPTION[196] = 298;
SERVER_ENCRYPTION[197] = 278;
SERVER_ENCRYPTION[ServerProt.SLEEP_INCORRECT] = 247;
SERVER_ENCRYPTION[ServerProt.SLEEP_CLOSE] = 286;
SERVER_ENCRYPTION[ServerProt.PLAYER_STAT_FATIGUE_ASLEEP] = 346;
SERVER_ENCRYPTION[ServerProt.SLEEP_OPEN] = 144;
SERVER_ENCRYPTION[ServerProt.PLAYER_STAT_FATIGUE] = 23;
SERVER_ENCRYPTION[ServerProt.MESSAGE_ONTOP] = 913;
SERVER_ENCRYPTION[ServerProt.MESSAGE_GAME] = 812;
SERVER_ENCRYPTION[ServerProt.LAST_LOGIN_INFO] = 765;
SERVER_ENCRYPTION[ServerProt.TELEPORT_BUBBLE] = 432;
SERVER_ENCRYPTION[ServerProt.SYNTH_SOUND] = 176;
SERVER_ENCRYPTION[ServerProt.DUEL_CONFIRM_OPEN] = 935;
SERVER_ENCRYPTION[ServerProt.DUEL_ACCEPTED] = 452;
SERVER_ENCRYPTION[ServerProt.DUEL_RECIPIENT_ACCEPTED] = 542;
SERVER_ENCRYPTION[ServerProt.PLAYER_STAT_UPDATE] = 45;
SERVER_ENCRYPTION[ServerProt.INVENTORY_ITEM_REMOVE] = 346;
SERVER_ENCRYPTION[ServerProt.UPDATE_INV_PARTIAL] = 65;
SERVER_ENCRYPTION[ServerProt.BANK_UPDATE] = 637;
SERVER_ENCRYPTION[ServerProt.DUEL_SETTINGS] = 62;
SERVER_ENCRYPTION[ServerProt.DUEL_ITEMS] = 354;
SERVER_ENCRYPTION[ServerProt.TRADE_CONFIRM_OPEN] = 123;
SERVER_ENCRYPTION[ServerProt.DUEL_CLOSE] = 34;
SERVER_ENCRYPTION[ServerProt.DUEL_OPEN] = 912;
SERVER_ENCRYPTION[ServerProt.PLAYER_STAT_EXPERIENCE_UPDATE] = 812;
SERVER_ENCRYPTION[ServerProt.BANK_CLOSE] = 834;
SERVER_ENCRYPTION[ServerProt.BANK_OPEN] = 698;
SERVER_ENCRYPTION[223] = 324;
SERVER_ENCRYPTION[224] = 872;
SERVER_ENCRYPTION[225] = 912;
SERVER_ENCRYPTION[ServerProt.PLAYER_QUEST_LIST] = 438;
SERVER_ENCRYPTION[ServerProt.PRAYER_STATUS] = 765;
SERVER_ENCRYPTION[ServerProt.GAME_SETTINGS] = 344;
SERVER_ENCRYPTION[ServerProt.TRADE_ACCEPTED] = 731;
SERVER_ENCRYPTION[230] = 625;
SERVER_ENCRYPTION[231] = 783;
SERVER_ENCRYPTION[232] = 176;
SERVER_ENCRYPTION[ServerProt.SHOP_CLOSE] = 658;
SERVER_ENCRYPTION[ServerProt.SHOP_OPEN] = 128;
SERVER_ENCRYPTION[ServerProt.TRADE_RECIPIENT_ACCEPTED] = 854;
SERVER_ENCRYPTION[ServerProt.TRADE_ITEMS] = 489;
SERVER_ENCRYPTION[ServerProt.TRADE_CLOSE] = 85;
SERVER_ENCRYPTION[ServerProt.TRADE_OPEN] = 6;
SERVER_ENCRYPTION[ServerProt.APPEARANCE] = 865;
SERVER_ENCRYPTION[ServerProt.REGION_ENTITY_UPDATE] = 43;
SERVER_ENCRYPTION[ServerProt.PLAYER_DIED] = 573;
SERVER_ENCRYPTION[ServerProt.PLAYER_STAT_EQUIPMENT_BONUS] = 132;
SERVER_ENCRYPTION[ServerProt.PLAYER_STAT_LIST] = 527;
SERVER_ENCRYPTION[ServerProt.REBUILD_NORMAL] = 235;
SERVER_ENCRYPTION[ServerProt.OPTION_LIST_CLOSE] = 434;
SERVER_ENCRYPTION[ServerProt.OPTION_LIST] = 658;
SERVER_ENCRYPTION[ServerProt.REGION_NPC_UPDATE] = 912;
SERVER_ENCRYPTION[ServerProt.NPC_INFO] = 825;
SERVER_ENCRYPTION[ServerProt.REGION_WALL_OBJECTS] = 298;
SERVER_ENCRYPTION[ServerProt.REGION_PLAYER_UPDATE] = 753;
SERVER_ENCRYPTION[251] = 282;
SERVER_ENCRYPTION[ServerProt.UPDATE_INV_FULL] = 652;
SERVER_ENCRYPTION[ServerProt.REGION_OBJECTS] = 439;
SERVER_ENCRYPTION[ServerProt.REGION_GROUND_ITEMS] = 629;
SERVER_ENCRYPTION[ServerProt.PLAYER_INFO] = 945;
